### ISSUE TITLE
dav1d-1.3.0 build issue (Meson 0.47.0 or higher required)

### ISSUE THREAD

**Issue by veikk0** [phoronix-test-suite/test-profiles#104]
Installation of the dav1d-1.3.0 test failed for me on Linux Mint 19.1 because the version of Meson in the Ubuntu 18.04 repositories is too old. The log showed the following error:

```
The Meson build system
Version: 0.45.1
Source dir: /home/veikk0/.phoronix-test-suite/installed-tests/pts/dav1d-1.3.0/dav1d-0.4.0
Build dir: /home/veikk0/.phoronix-test-suite/installed-tests/pts/dav1d-1.3.0/dav1d-0.4.0/build
Build type: native build

meson.build:25:0: ERROR: Meson version is 0.45.1 but project requires >= 0.47.0.
```
I solved the issue by removing Meson (`sudo aptitude remove meson`) and installing a more up-to-date one via pip (`sudo pip3 install meson`). I assume `pip3 install --user meson` would also work.

Another thing that happened was that the test installation had to re-download all the test video files that it had already downloaded during the failed installation. Attempting to compile the software before downloading the video files could save time and bandwidth in similar instances.

**Comment by michaellarabel** [comment]
The Meson build issue is outside of the scope of PTS. There isn't anything that can be done from the PTS side when the Meson version available by the OS is too old, short of failing and letting the user know. I've tried with the pip'ed Meson on some distributions in the past and sometimes caused collisions on the system with other tests.

In regards to the video files being deleted, that was done to save space but had already been thinking of changing that to match the behavior done by other tests, so with the next update will keep those files preserved. Thanks.
