### ISSUE TITLE
Add Windows install script to dav1d and libaom profiles

### ISSUE THREAD

**Issue by EwoutH** [phoronix-test-suite/test-profiles#105]

**Comment by michaellarabel** [comment]
Is there any official Windows builds of dav1d?

**Comment by JJAYL** [comment]
[Here](https://code.videolan.org/videolan/dav1d/-/jobs/artifacts/0.5.2/download?job=build-win64) is the URL for dav1d 0.5.2. I found it on their gitlab. I selected the tag and clicked the download button on the right and selected build-win64. They don't seem to have official windows builds for 0.5.0

**Comment by michaellarabel** [comment]
@JJAYL, thanks yeah ended up discovering that after the earlier post. So since October the dav1d test profile has supported Windows using those official binaries. Though not aware of any libaom windows binaries per the other part of this ticket.

**Comment by EwoutH** [comment]
@michaellarabel Here are libaom Windows build: https://ci.appveyor.com/project/marcomsousa/build-aom/history

**Comment by michaellarabel** [comment]
pts/aom-av1-2.0.1 now has Windows support.
