### ISSUE TITLE
Update SVT-VP9 profile to 0.1.0

### ISSUE THREAD

**Issue by EwoutH** [phoronix-test-suite/test-profiles#106]
[SVT-VP9 0.1.0](https://github.com/OpenVisualCloud/SVT-VP9/releases/tag/v0.1.0) got tagged, @michaellarabel could you update the profile? Maybe we could also use different encoder modes like SVT-AV1.

**Comment by michaellarabel** [comment]
Yep was already working on it after seeing the new release. Also had planned to specify the -tune options and add Windows support now that binaries are up.

**Comment by michaellarabel** [comment]
pts/svt-vp9-1.2.0 is now available with SVT-VP9 0.1, Windows support, and tune 0/1/2 options.
