### ISSUE TITLE
Add rav1e test profile

### ISSUE THREAD

**Issue by EwoutH** [phoronix-test-suite/test-profiles#107]
Add a test profile for the [rav1e](https://github.com/xiph/rav1e) AV1 video encoder. 

Currently a lot of performance improvements are made by adding SSSE3, AVX2 and NEON assembly code, so a git profile added to [linuxbenchmarking.com](http://linuxbenchmarking.com/?video-benchmarks) that runs on x86 (pre-Haswell and post Haswell) and ARMv8 would be a very welcome addition.

**Comment by EwoutH** [comment]
For the non-Git profile the [20191023](https://github.com/xiph/rav1e/releases/tag/20191023) pre-release can be used.

**Comment by michaellarabel** [comment]
I hadn't added a rav1e test profile previously as the performance is still rather poor, but anyhow, pts/rav1e is now available.

**Comment by EwoutH** [comment]
Thanks a lot! Could you also add a Git profile? Would be interessting to track progress (preferably on desktop SSSE3 andAVX2 and Arm NEON

**Comment by michaellarabel** [comment]
Will add it to my TODO list. Not sure about adding more tests that run daily though on LinuxBenchmarking.com as resources running tight so trying to avoid unnecessary power use.
