### ISSUE TITLE
Update rav1e test profile

### ISSUE THREAD

**Issue by EwoutH** [phoronix-test-suite/test-profiles#109]
Update the rav1e test profile to the [20191101](https://github.com/xiph/rav1e/releases/tag/20191101) pre-release.

> **Improvements**
> - More x86 assembly from dav1d
> - Validate the frame size to reject impossibly small frames.
> - Initial SSE4.1 support

**Comment by michaellarabel** [comment]
The test profile was updated to rav1e 0.1.
