### ISSUE TITLE
Update SVT-AV1 profile to 0.8.0

### ISSUE THREAD

**Issue by EwoutH** [phoronix-test-suite/test-profiles#119]
@michaellarabel Update the [SVT-AV1 profile to 0.8.0](https://github.com/OpenVisualCloud/SVT-AV1/releases/tag/v0.8.0) . All other settings can remain the same.

Thanks in advance :)

**Comment by michaellarabel** [comment]
The test profile was already updated today but thanks.

**Comment by EwoutH** [comment]
Great work, thanks a lot!

**Comment by EwoutH** [comment]
Could you update the SVT-AV1 test profile to [v0.8.4](https://github.com/OpenVisualCloud/SVT-AV1/releases/tag/v0.8.4)? It was release this weekend and contains over half a year of speed and quality improvements (compared to v0.8.0).

**Comment by EwoutH** [comment]
@michaellarabel SVT-AV1 [v0.8.5](https://github.com/AOMediaCodec/SVT-AV1/releases/tag/v0.8.5) was tagged yesterday. It may seem like an minor update due to the version number, but it's actually a huge improvement both speed, quality and feature wise.
