### ISSUE TITLE
omega-opm-2.tar.gz

### ISSUE THREAD

**Issue by MaXinjian** [phoronix-test-suite/test-profiles#120]
where can I found omega-opm-2.tar.gz for opm-git?

**Comment by michaellarabel** [comment]
This is an optional file that isn't  currently open-source / public, if you don't have access to the file you can still run the other tests/options.

**Comment by MaXinjian** [comment]
but options don't use omega-opm is only "upscale_relperm_benchmark", there is no opm-upscaling repo now.

======
if [ $1 = "upscale_relperm_benchmark" ]
then
        nice mpirun $MPIRUN_AS_ROOT_ARG -np $NPROC $MPI_MAP_BY --report-bindings $HOSTFILE ./opm-upscaling/build/bin/upscale_relperm_benchmark --tolerance-mb=1e-5 --max-strict-iter=4 > $LOG_FILE 2>&1
elif [ $1 = "flow_mpi_norne" ]
then
        cd opm-data/norne
        nice mpirun $MPIRUN_AS_ROOT_ARG -np $NPROC $MPI_MAP_BY --report-bindings $HOSTFILE ../../opm-simulators/build/bin/flow NORNE_ATW2013.DATA --tolerance-mb=1e-5 --max-strict-iter=4 > $LOG_FILE 2>&1
elif [ $1 = "flow_ebos_extra" ]
then
        cd opm-data/omega-opm
        nice mpirun $MPIRUN_AS_ROOT_ARG -np $NPROC $MPI_MAP_BY --report-bindings $HOSTFILE ../../opm-simulators/build/bin/flow OMEGA-0.DATA --tolerance-mb=1e-5 --max-strict-iter=4 > $LOG_FILE 2>&1
elif [ $1 = "flow_mpi_extra" ]
then
        cd opm-data/omega-opm
        nice mpirun $MPIRUN_AS_ROOT_ARG -np $NPROC $MPI_MAP_BY --report-bindings $HOSTFILE ../../opm-simulators/build/bin/flow OMEGA-0.DATA --tolerance-mb=1e-5 --max-strict-iter=4 > $LOG_FILE 2>&1
else
        nice mpirun $MPIRUN_AS_ROOT_ARG -np $NPROC $MPI_MAP_BY --report-bindings $HOSTFILE opm-simulators/build/bin/flow $1 --tolerance-mb=1e-5 --max-strict-iter=4 > $LOG_FILE 2>&1
fi
=======
