### ISSUE TITLE
pts/parboil-1.2.1 not working with Python 3

### ISSUE THREAD

**Issue by chenming1986** [phoronix-test-suite/test-profiles#127]
The parboil benchmark contains some syntax that are not compatible with Python 3, for example, print "". Since Python 2 is already end of life and is no longer supported by distros like Clear Linux, is there any plan to update the benchmark to work with Python 3?

Thanks.

Below is the output of ```phoronix-test-suite debug-run parboil-1.2.1``` on Clear Linux 32100:
```
========================================
Parboil (Run 1 of 1)
========================================


Test Run Command: cd /home/ming/.phoronix-test-suite/installed-tests/pts/parboil-1.2.1/ && ./parboil stencil omp_base default 2>&1

Traceback (most recent call last):
  File "./parboil", line 8, in <module>
    import driver
  File "/home/ming/.phoronix-test-suite/installed-tests/pts/parboil-1.2.1/parboil-2.5-tree/driver/__init__.py", line 16
    print "Parboil parallel benchmark suite, version 0.2"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Parboil parallel benchmark suite, version 0.2")?

The test quit with a non-zero exit status.


E: SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Parboil parallel benchmark suite, version 0.2")?


Log File At: /home/ming/.phoronix-test-suite/installed-tests/pts/parboil-1.2.1/parboil-1.2.1-1579516207-1.log



The following tests failed to properly run:

        - pts/parboil-1.2.1: Test: OpenMP Stencil

```

**Comment by michaellarabel** [comment]
The Phoronix Test Suite is tracking the upstream Parboil (http://impact.crhc.illinois.edu/parboil/parboil.aspx). When checking just now, it appears Parboil hasn't seen any new releases beyond what is already incorporated in the Phoronix Test Suite, so this would be an upstream issue with them regarding porting to Python 3.

**Comment by chenming1986** [comment]
Thanks for the reply, Michael. I'm closing the issue given no newer version of parboil is available for now.
