### ISSUE TITLE
pts/apitrace install fail due to redeclipse-1-trace.7z not found

### ISSUE THREAD

**Issue by yunyings** [phoronix-test-suite/test-profiles#13]
When trying to install pts/apitrace for Phoronix Test Suite 7.8.0on on a Kabylake NUC(NUC7i5DNB) which is running Ubuntu 17.10, I always get same failure:
{noformat}
            Download Failed: http://www.phoronix-test-suite.com/benchmark-files/redeclipse-1-trace.7z
            Downloading of needed test files failed.
{noformat}

It turns out that the file is not available at http://www.phoronix-test-suite.com/benchmark-files/.
Is this an issue supposed to be fixed? 

Detailed logs and system information attached.
[apitrace_install_fail.log](https://github.com/phoronix-test-suite/test-profiles/files/1773739/apitrace_install_fail.log)

**Comment by michaellarabel** [comment]
This test is now marked as deprecated as it hasn't been useful now in years.
