### ISSUE TITLE
compress-zstd-1.1.2: the embedded patch fails to apply

### ISSUE THREAD

**Issue by chenming1986** [phoronix-test-suite/test-profiles#132]
The embedded patch "portable-header-prefix.patch" fails to apply during installing compress-zstd-1.1.2. It seems that the line breaks at line 9/11/25/34/43 in the [original commit](https://github.com/phoronix-test-suite/test-profiles/pull/128/commits/6d3284ce0f3a5bc3af4caa3c6db47dba1d4c9844) are missing from the final [install.sh](https://github.com/phoronix-test-suite/test-profiles/blob/master/pts/compress-zstd-1.1.2/install.sh).

Snippet from build.log:
```
patching file programs/Makefile
patch: **** malformed patch at line 17: @@ -98,7 +103,7 @@ endif
```

**Comment by chenming1986** [comment]
Attaching the patch towards pts/compress-zstd-1.1.2
https://gist.github.com/chenming1986/14230227771dd0d070393174043aebbb

@michaellarabel could you please review? Thanks.

**Comment by michaellarabel** [comment]
pts/compress-zstd-1.1.3 should now be available with the updated patch. Thanks.

**Comment by chenming1986** [comment]
@michaellarabel thanks for taking care of this, but the patch attached in this issue was supposed to be applied on top of compress-zstd-1.1.2, not to expand in install.sh.
To simplify I created another PR #137 that adds a complete working profile compress-zstd-1.1.4. Please check and sorry for any confusion caused.

**Comment by chenming1986** [comment]
Can we re-open this issue since it still exists as mentioned in the last comment?
