### ISSUE TITLE
pts/cassandra-1.0.2 - 3.11.4 No longer availible, replaced with 3.11.6

### ISSUE THREAD

**Issue by EndlessEden** [phoronix-test-suite/test-profiles#135]
Recently(atleast at the time of posting) all of the mirrors for apache-cassandra 3.11.4-bin have been removed, the only 3.11.4 host (ibiblio.org) remaining fails checksums. Please update the test.

**Comment by michaellarabel** [comment]
pts/cassandra-1.0.3 is now available with an updated list of mirrors for 3.11.4.
