### ISSUE TITLE
Feature Request: Geolocation for mirrors

### ISSUE THREAD

**Issue by EndlessEden** [phoronix-test-suite/test-profiles#136]
One of my largest annoyances is that installing test files, uses mirrors of regions of which are heavily throttled. Backbone connections to the EU and NA regions are heavily throttled with Asia, Parts of Germany and NL being more consistently faster.

In leue of having local mirrors as a option, it would be significantly better if some form of geo-location was preformed prior to downloading test depends and choosing mirrors accordingly.

**Comment by michaellarabel** [comment]
Within your ~/.phoronix-test-suite/user-config.xml or /etc/phoronix-test-suite.xml is a "PromptForDownloadMirror" that can be set to TRUE if you want to manually select your mirror for download.

But aside from that no GeoIP auto selector is planned as many mirrors only have one or two mirrors and most enterprise users of PTS are already using `phoronix-test-suite make-download-cache` and the like for generating their own cache on their LAN/intranet, etc.
