### ISSUE TITLE
pts/iozone-1.9.5 compilation fails with GCC 10

### ISSUE THREAD

**Issue by antoinebj** [phoronix-test-suite/test-profiles#139]
Error due to `nocommon` flag active by default in GCC 10.

```/usr/bin/ld: libbif.o:(.bss+0x8): multiple definition of `junk'; iozone_linux-AMD64.o:(.bss+0x340e0): first defined here```

**Comment by antoinebj** [comment]
I did not find an environment variable that could pass the `-fcommon` switch to GCC, so I had to change `install.sh`.
`make linux-AMD64`
Becomes:
`make CFLAGS=-fcommon linux-AMD64`

**Comment by michaellarabel** [comment]
Thanks, fixed in pts/iozone-1.9.5.
