### ISSUE TITLE
pts/mysqlslap-1.0.8 compilation fails with GCC 10

### ISSUE THREAD

**Issue by antoinebj** [phoronix-test-suite/test-profiles#141]
Error due to `nocommon` flag active by default in GCC 10.

```mysqlslap-1.0.8/mariadb-10.3.8/extra/mariabackup/xbstream.c:48: multiple definition of `datasink_buffer'; CMakeFiles/mbstream.dir/ds_buffer.c.o:(.data.rel.local+0x0): first defined here```

**Comment by michaellarabel** [comment]
This is now fixed by pts/mysqlslap-1.1.0 that upgrades against MariaDB 10.5.2 and in turn fixes the GCC 10 build issue.
