### ISSUE TITLE
pts/namd-1.1.0 fails to run on Windows

### ISSUE THREAD

**Issue by antoinebj** [phoronix-test-suite/test-profiles#144]
It complains about a missing dependency.

cygcheck tells me MSVCR100.dll is missing.

There is a warning upon installation that the VC++ 2010 runtime must be installed, but it turns out that the provided link is for the 32-bits one. You might want to update it for 64-bit as the majority of people will probably be running a 64-bit Windows:
https://www.microsoft.com/en-us/download/details.aspx?id=13523

However, after that, the test still fails, but with no output, and nothing in the log at all.
I currently have no idea how to fix that.

**Comment by michaellarabel** [comment]
I have been unable to reproduce this issue on multiple clean installs of Windows 10. Seems to be working fine during my tests. Have you been able to get it to run yet?

**Comment by antoinebj** [comment]
Not yet, but I haven't tried lately. I'll test again with a new Windows installation in the coming week.

**Comment by michaellarabel** [comment]
Just tried again with the latest pts/namd-1.2.1 and it's running fine on Windows after installing the VC++ 2010 runtime.
