### ISSUE TITLE
pts/java-gradle-perf fails to install/run

### ISSUE THREAD

**Issue by mo5h** [phoronix-test-suite/test-profiles#146]
Due to a change with how Spring hosts their maven repositories, the http:// URLs now result in 403s 
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'reactor-core'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve org.springframework.build.gradle:propdeps-plugin:0.0.7.
     Required by:
         :reactor-core:2.5.0.BUILD-SNAPSHOT
      > Could not resolve org.springframework.build.gradle:propdeps-plugin:0.0.7.
         > Could not get resource 'http://repo.spring.io/plugins-release/org/springframework/build/gradle/propdeps-plugin/0.0.7/propdeps-plugin-0.0.7.pom'.
            > Could not HEAD 'http://repo.spring.io/plugins-release/org/springframework/build/gradle/propdeps-plugin/0.0.7/propdeps-plugin-0.0.7.pom'. Received status code 403 from server: Forbidden
   > Could not resolve io.spring.gradle:spring-io-plugin:0.0.4.RELEASE.
     Required by:
         :reactor-core:2.5.0.BUILD-SNAPSHOT
      > Could not resolve io.spring.gradle:spring-io-plugin:0.0.4.RELEASE.
         > Could not get resource 'http://repo.spring.io/plugins-release/io/spring/gradle/spring-io-plugin/0.0.4.RELEASE/spring-io-plugin-0.0.4.RELEASE.pom'.
            > Could not HEAD 'http://repo.spring.io/plugins-release/io/spring/gradle/spring-io-plugin/0.0.4.RELEASE/spring-io-plugin-0.0.4.RELEASE.pom'. Received status code 403 from server: Forbidden

Solution is to replace the http:// urls with https:// urls
See example of it working here:
https://openbenchmarking.org/test/farrantino/java-gradle-perf

https://stackoverflow.com/questions/59767726/why-i-have-http-403-from-repo-spring

**Comment by michaellarabel** [comment]
Thanks, if you want to submit your fix as a pull request happy to pull it in.

**Comment by michaellarabel** [comment]
Should be fixed now with the merge and also updating against upstream Reactor. Thanks!
