### ISSUE TITLE
pts/pgbench Scaling issues on high CPU, high mem systems.  Inaccurate results.

### ISSUE THREAD

**Issue by jboero** [phoronix-test-suite/test-profiles#152]
Hi I've been a fan of the pgbench profile for quite a few years but it seems this test needs major updating for high cpu and mem systems.  Current test results are highly inaccurate.  There are two issues here - one during initialization and one during test runs.

1. During initialization of the test database, SCALING_FACTOR is determined by your selection of BUFFER/MOSTLY_CACHE/ON_DISK and multiplying a factor by $SYS_MEMORY which in my case is 128GB.  The initialization proceeds to completely fill the 1 TB home partition and enabling "-d" for debug tracing the Postgres pgbench binary it shows it's attempting to create "2580400000" tuples which will seemingly take forever and fill any partition without any errors or feedback.  I question the apples-to-apples comparison of a benchmark that generates and uses a different size database across platforms.  Would it make sense to replace uncapped BUFFER/CACHE/DISK calculated options with fixed database size options?

As a workaround to get this running, you can locally adjust or remove SCALING_FACTOR on this line of the pgbench script (not binary):
[line](https://github.com/phoronix-test-suite/test-profiles/blob/cadb82b48f6835678f80d9dd3d91ce83ba8a9bb3/pts/pgbench-1.9.1/install.sh#L134)

2. Once you adjust SCALING_FACTOR down you can actually complete a database creation/initialization and run a test.  If you enable "-d" for debug on the pgbench binary on [this line](https://github.com/phoronix-test-suite/test-profiles/blob/cadb82b48f6835678f80d9dd3d91ce83ba8a9bb3/pts/pgbench-1.9.1/install.sh#L158), it becomes apparent there is another issue with the test itself.  The parallel clients are calculated based on $NUM_CPU_PHYSICAL_CORES, which in my case is 20.  A heavy contention test multiplies that by 16.  With debug flag enabled it becomes apparent that the postgres service itself is configured to run with a default maximum client count of 100 which is far below my 320.  The test in debug mode is silently dumping out piles errors when clients fail to connect even though the test is still running and being timed:
```
FATAL:  sorry, too many clients already
connection to database "pgbench" failed:
```
Again would it make sense to replace calculated variables which yield wildly different test conditions on different systems with constant number options of client connect?  As CPU core counts increase this test will become more important and more inaccurate as a reflection of system performance.  Maybe we could select a fixed number of clients - 100, 1000, 100000 etc?

**Comment by michaellarabel** [comment]
The pgbench test profile parameters are based originally on what the PostgreSQL crew laid out at https://wiki.postgresql.org/wiki/Pgbenchtesting for their recommended pgbench testing. But yes I actually would prefer a static number of clients, etc.When I update the test profile next for the next major version of pgbench I'll look at making it static similar to the mysqlslap test profile or in the interim if you have any other specific suggestions or suitable values you've found for testing, happy to try them out on some of my larger systems as well.

**Comment by jboero** [comment]
Excellent thanks for the rapid response!

**Comment by michaellarabel** [comment]
pts/pgbench-1.10 test profile will be available via Openbenchmarking in a few minutes that rebases against PostgreSQL 13 and in the process restructures the handling of all the options to be static and other improvements. Thanks.
