### ISSUE TITLE
speed up building of aom-av1 test

### ISSUE THREAD

**Issue by veikk0** [phoronix-test-suite/test-profiles#158]
The following cmake flags will reduce the build time of the aom test by about 60%: `-DENABLE_DOCS=0 -DENABLE_TESTS=0 -DCONFIG_AV1_DECODER=0`

The first one disables documentation, second disables test (these are only useful for aom developers), and the last one disables the decoder (not needed, since this is an encoding test).

Build time went from about 2 minutes to 50 seconds on a 6-core 12-thread machine.

**Comment by michaellarabel** [comment]
Thanks, pts/aom-av1-2.1.2 is now available with these options set.
