### ISSUE TITLE
Download failed for system-decompress-gzip-1.1.0 and system-decompress-zlib-1.0.1

### ISSUE THREAD

**Issue by veikk0** [phoronix-test-suite/test-profiles#159]
How to reproduce: run `phoronix-test-suite install system-decompress-gzip system-decompress-zlib`

Output of the command:

    Phoronix Test Suite v9.8.0

    To Install:    pts/system-decompress-gzip-1.1.0
    To Install:    pts/system-decompress-zlib-1.0.1

    Determining File Requirements ...............................................................................
    Searching Download Caches ...................................................................................

    2 Tests To Install
        3 Files To Download [438MB]
        31 Seconds Estimated Install Time

    pts/system-decompress-gzip-1.1.0:
        Test Installation 1 of 2
        1 File Needed [219 MB / 1 Minute]
        Downloading: qt-everywhere-opensource-src-5.0.0.tar.gz                                            [219MB]
            Download Failed: http://releases.qt-project.org/qt5/5.0.0/single/qt-everywhere-opensource-src-5.0.0.tar.gz
            Downloading of needed test files failed.
    pts/system-decompress-zlib-1.0.1:
        Test Installation 2 of 2
        2 Files Needed [220 MB / 1 Minute]
        Downloading: zlib-1.2.7.tar.bz2                                                                  [0.48MB]
            Download Failed: http://softlayer-dal.dl.sourceforge.net/project/libpng/zlib/1.2.7/zlib-1.2.7.tar.bz2
            Downloading of needed test files failed.

    The following tests failed to install:

      - pts/system-decompress-gzip-1.1.0
      - pts/system-decompress-zlib-1.0.1

**Comment by michaellarabel** [comment]
Thanks, system-decompress-gzip-1.1.1 and system-decompress-zlib-1.0.2 are now available with updated mirrors.
