### ISSUE TITLE
pts/osbench create_process.exe missing on Windows

### ISSUE THREAD

**Issue by mirror176** [phoronix-test-suite/test-profiles#160]
Log file is 0 bytes after running. osbench-1.0.2\osbench-win64-20170529.zip only has 4 exes: create_files, create_threads, launch_programs, mem_alloc. Should the test be excluded on Windows or can a new zip file with the executable be created? the *nix downloads get a source code archive from October 2017 with code for the additional file. Test run included below:

.\phoronix-test-suite debug-run osbench
Starting the Phoronix Test Suite

         Evaluating External Test Dependencies ..........................................................................

Phoronix Test Suite v10.0.0m1

    Installed:     pts/osbench-1.0.2

OSBench:
pts/osbench-1.0.2
OS Test Configuration
1: Create Files
2: Create Processes
3: Create Threads
4: Launch Programs
5: Memory Allocations
6: Test All Options
** Multiple items can be selected, delimit by a comma. **
Test: 2

========================================
Phoronix Test Suite v10.0.0m1
System Information
========================================

  PROCESSOR:          Intel Core i7-3820 @ 3.60GHz
    Core Count:       4
    Thread Count:     8
    Cache Size:       256 MB
    Core Family:      Sandy Bridge

  GRAPHICS:           NVIDIA GeForce GTX 660 2GB
    Display Driver:   445.98 (26.21.14.4598)
    Screen:           1920x1080

  MOTHERBOARD:        ASUS SABERTOOTH X79
    BIOS Version:     4801
    Network:          AnchorFree TAP-Windows V9 + VirtualBox Host-Only

  MEMORY:             4 x 8192 MB 1333MHz F3-12800CL10-8GBZ

  DISK:               1863GB WDC WD2003FZEX-00Z4SA0
                      + 466GB Samsung SSD 850 EVO 500GB
                      + 466GB Samsung Portable SSD T3 USB
    File-System:      NTFS

  OPERATING SYSTEM:   Microsoft Windows 10 Pro Build 19041
    Kernel:           10.0 (x86_64)
    Compiler:         GCC 8.1.0 + Clang 10.0.0
    Security:         __user pointer sanitization: Disabled
                      + Retpoline: Full
                      + IBPB: Always
                      + IBRS: Enabled
                      + STIBP: Enabled
                      + KPTI Enabled: Yes
                      + PTE Inversion: Yes

========================================
OSBench (Run 1 of 1)
========================================

Test Run Command: cd C:\Users\Bomarc\.phoronix-test-suite\installed-tests\\pts/osbench-1.0.2\ && ./osbench create_processes.exe 2>&1

./osbench: line 3: ./create_processes.exe: No such file or directory

Result Key: #_RESULT_#

Template Line: #_RESULT_# us / alloc

Result Parsing Search Key: "us"

Result Line:

No Test Results

Result Key: #_RESULT_#

Template Line: #_RESULT_# ns / alloc

Result Parsing Search Key: "ns"

Result Line:

No Test Results

The test run did not produce a result.

Log File At: C:\Users\Bomarc\.phoronix-test-suite\installed-tests\pts\osbench-1.0.2\osbench-1.0.2-1600878209-1.log

The following tests failed to properly run:

    - pts/osbench-1.0.2: Test: Create Processes

[NOTICE] unlink(C:\Users\Bomarc\.phoronix-test-suite\result_viewer_lock): Resource temporarily unavailable:38
PS E:\Users\Bomarc\Downloads\benchmarks\phoronix-test-suite-10.0.0m1>

**Comment by michaellarabel** [comment]
The upstream osbench doesn't provide a create_processes test for Windows.
