### ISSUE TITLE
Windows: Several Unigine tests failures

### ISSUE THREAD

**Issue by mirror176** [phoronix-test-suite/test-profiles#163]
unigine-heaven download has been replaced with a different file of the same name:
      <MD5>2477dcb2d7072b96abc6a1ae447a960c</MD5>
      <SHA256>497865a09af205a7d2e8812bfc2dd54870216cc1e95541b63cef89a4433b0e5f</SHA256>
      <FileSize>259708359</FileSize>
      <PlatformSpecific>Windows</PlatformSpecific>

Tropics, Sanctuary, and Super fail to install; msiexec is not found while the install_windows.sh script is running. I don't think it is treated as an install failure as tests will then try to be ran anyway  if requested but no useful output results.

After manually installing, Super failed to produce a result while having neovim v0.4.3 installed through chocolatey as it appeared to get involved execution of the `cat /cygdrive/c/*sers/*/Superposition/automation/* > $LOG_FILE` command in unigine-super. Appears to function with neovim removed.
I had found this in the debug-run-benchmark output:
C:\tools\neovim\Neovim\bin\cat.exe: /cygdrive/c/Users/Bomarc/Superposition/automation/log-2020923_1547.txt: No such file or directory

.\phoronix-test-suite debug-install unigine-heaven unigine-sanctuary unigine-super unigine-tropics unigine-valley
Starting the Phoronix Test Suite

     To Install:    pts/unigine-heaven-1.6.4
To Install:    pts/unigine-sanctuary-1.6.4
To Install:    pts/unigine-super-1.0.6
To Install:    pts/unigine-tropics-1.6.4
To Install:    pts/unigine-valley-1.1.8

========================================
Installing Test: pts/unigine-heaven-1.6.4
========================================

===========================================
Downloading Files: pts/unigine-heaven-1.6.4
===========================================

============================================
Installing Test: pts/unigine-sanctuary-1.6.4
============================================

Downloading Files: pts/unigine-sanctuary-1.6.4
==============================================

C:\Users\Bomarc\.phoronix-test-suite\test-profiles/pts/unigine-sanctuary-1.6.4/install_windows.sh: line 6: msiexec.exe: command not found

========================================
Installing Test: pts/unigine-super-1.0.6
========================================

==========================================
Downloading Files: pts/unigine-super-1.0.6
==========================================

C:\Users\Bomarc\.phoronix-test-suite\test-profiles/pts/unigine-super-1.0.6/install_windows.sh: line 13: msiexec: command not found

==========================================
Installing Test: pts/unigine-tropics-1.6.4
==========================================

============================================
Downloading Files: pts/unigine-tropics-1.6.4
============================================

C:\Users\Bomarc\.phoronix-test-suite\test-profiles/pts/unigine-tropics-1.6.4/install_windows.sh: line 9: msiexec: command not found

========================================
Installing Test: pts/unigine-valley-1.1.8
========================================

===========================================
Downloading Files: pts/unigine-valley-1.1.8
===========================================

**Comment by michaellarabel** [comment]
The unigine test hashes were recently fixed in updated tests, so this should be fixed. Thanks.
