### ISSUE TITLE
Windows: cpuminer-opt fails/crashes due to lack of avx2 on i7-3820

### ISSUE THREAD

**Issue by mirror176** [phoronix-test-suite/test-profiles#168]
Can the test be set with more compatibility checks so it could avoid being offered for this hardware? Would there be any value in compiling and running non-avx2 versions of it?

 .\phoronix-test-suite debug-benchmark cpuminer-opt
Starting the Phoronix Test Suite

         Evaluating External Test Dependencies ................................................................................................................................................

Phoronix Test Suite v10.0.0m1

    Installed:     pts/cpuminer-opt-1.3.0

Cpuminer-Opt 3.8.8.1:
pts/cpuminer-opt-1.3.0
Processor Test Configuration
1: lbry
2: sha256t
3: skein
4: myr-gr
5: m7m
6: deep
7: Test All Options
** Multiple items can be selected, delimit by a comma. **
Algorithm: 7

========================================
Phoronix Test Suite v10.0.0m1
System Information
========================================

  PROCESSOR:          Intel Core i7-3820 @ 3.60GHz
    Core Count:       4
    Thread Count:     8
    Cache Size:       256 MB
    Core Family:      Sandy Bridge

  GRAPHICS:           NVIDIA GeForce GTX 660 2GB
    Display Driver:   445.98 (26.21.14.4598)
    Screen:           1920x1080

  MOTHERBOARD:        ASUS SABERTOOTH X79
    BIOS Version:     4801
    Network:          AnchorFree TAP-Windows V9 + VirtualBox Host-Only

  MEMORY:             4 x 8192 MB 1333MHz F3-12800CL10-8GBZ

  DISK:               1863GB WDC WD2003FZEX-00Z4SA0
                      + 466GB Samsung SSD 850 EVO 500GB
                      + 466GB Samsung Portable SSD T3 USB
    File-System:      NTFS

  OPERATING SYSTEM:   Microsoft Windows 10 Pro Build 19041
    Kernel:           10.0 (x86_64)
    Compiler:         GCC 8.1.0 + Clang 10.0.0
    Security:         __user pointer sanitization: Disabled
                      + Retpoline: Full
                      + IBPB: Always
                      + IBRS: Enabled
                      + STIBP: Enabled
                      + KPTI Enabled: Yes
                      + PTE Inversion: Yes

========================================
Cpuminer-Opt (Run 1 of 1)
========================================

Test Run Command: cd C:\Users\Bomarc\.phoronix-test-suite\installed-tests\\pts/cpuminer-opt-1.3.0\ && ./cpuminer-opt -a m7m 2>&1

         **********  cpuminer-opt 3.8.8.1  ***********
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

CPU:         Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz.
SW built on May 11 2018 with GCC 5.3.1.
CPU features: SSE2 AES SSE4.2 AVX.
SW features: SSE2 AES SSE4.2 AVX AVX2.
Algo features: SHA.
The SW build requires a CPU with AES and AVX2!

Result Key: #_RESULT_#

Template Line: [2017-12-10 18:07:01] Benchmark: #_RESULT_# MH/s

Result Parsing Search Key: "MH/s"

Result Line:

No Test Results

Result Key: #_RESULT_#

Template Line: [2017-12-10 18:07:01] Benchmark: #_RESULT_# kH/s

Result Parsing Search Key: "kH/s"

Result Line:

No Test Results

The test run did not produce a result.

Log File At: C:\Users\Bomarc\.phoronix-test-suite\installed-tests\pts\cpuminer-opt-1.3.0\cpuminer-opt-1.3.0-1601096852-1.log

========================================
Cpuminer-Opt (Run 1 of 1)
========================================

Test Run Command: cd C:\Users\Bomarc\.phoronix-test-suite\installed-tests\\pts/cpuminer-opt-1.3.0\ && ./cpuminer-opt -a deep 2>&1

./cpuminer-opt: line 3:   414 Illegal instruction     ./cpuminer-avx2.exe --quiet --time-limit=30 --benchmark $@ > $LOG_FILE

Result Key: #_RESULT_#

Template Line: [2017-12-10 18:07:01] Benchmark: #_RESULT_# MH/s

Result Parsing Search Key: "MH/s"

Result Line:

No Test Results

Result Key: #_RESULT_#

Template Line: [2017-12-10 18:07:01] Benchmark: #_RESULT_# kH/s

Result Parsing Search Key: "kH/s"

Result Line:

No Test Results

The test run did not produce a result.

Log File At: C:\Users\Bomarc\.phoronix-test-suite\installed-tests\pts\cpuminer-opt-1.3.0\cpuminer-opt-1.3.0-1601096880-1.log

========================================
Cpuminer-Opt (Run 1 of 1)
========================================

Test Run Command: cd C:\Users\Bomarc\.phoronix-test-suite\installed-tests\\pts/cpuminer-opt-1.3.0\ && ./cpuminer-opt -a lbry 2>&1

         **********  cpuminer-opt 3.8.8.1  ***********
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

CPU:         Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz.
SW built on May 11 2018 with GCC 5.3.1.
CPU features: SSE2 AES SSE4.2 AVX.
SW features: SSE2 AES SSE4.2 AVX AVX2.
Algo features: AVX2 SHA.
The SW build requires a CPU with AES and AVX2!

Result Key: #_RESULT_#

Template Line: [2017-12-10 18:07:01] Benchmark: #_RESULT_# MH/s

Result Parsing Search Key: "MH/s"

Result Line:

No Test Results

Result Key: #_RESULT_#

Template Line: [2017-12-10 18:07:01] Benchmark: #_RESULT_# kH/s

Result Parsing Search Key: "kH/s"

Result Line:

No Test Results

The test run did not produce a result.

Log File At: C:\Users\Bomarc\.phoronix-test-suite\installed-tests\pts\cpuminer-opt-1.3.0\cpuminer-opt-1.3.0-1601096890-1.log

========================================
Cpuminer-Opt (Run 1 of 1)
========================================

Test Run Command: cd C:\Users\Bomarc\.phoronix-test-suite\installed-tests\\pts/cpuminer-opt-1.3.0\ && ./cpuminer-opt -a skein 2>&1

         **********  cpuminer-opt 3.8.8.1  ***********
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

CPU:         Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz.
SW built on May 11 2018 with GCC 5.3.1.
CPU features: SSE2 AES SSE4.2 AVX.
SW features: SSE2 AES SSE4.2 AVX AVX2.
Algo features: AVX2 SHA.
The SW build requires a CPU with AES and AVX2!

Result Key: #_RESULT_#

Template Line: [2017-12-10 18:07:01] Benchmark: #_RESULT_# MH/s

Result Parsing Search Key: "MH/s"

Result Line:

No Test Results

Result Key: #_RESULT_#

Template Line: [2017-12-10 18:07:01] Benchmark: #_RESULT_# kH/s

Result Parsing Search Key: "kH/s"

Result Line:

No Test Results

The test run did not produce a result.

Log File At: C:\Users\Bomarc\.phoronix-test-suite\installed-tests\pts\cpuminer-opt-1.3.0\cpuminer-opt-1.3.0-1601096901-1.log

========================================
Cpuminer-Opt (Run 1 of 1)
========================================

Test Run Command: cd C:\Users\Bomarc\.phoronix-test-suite\installed-tests\\pts/cpuminer-opt-1.3.0\ && ./cpuminer-opt -a myr-gr 2>&1

         **********  cpuminer-opt 3.8.8.1  ***********
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

CPU:         Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz.
SW built on May 11 2018 with GCC 5.3.1.
CPU features: SSE2 AES SSE4.2 AVX.
SW features: SSE2 AES SSE4.2 AVX AVX2.
Algo features: AES AVX2.
The SW build requires a CPU with AES and AVX2!

Result Key: #_RESULT_#

Template Line: [2017-12-10 18:07:01] Benchmark: #_RESULT_# MH/s

Result Parsing Search Key: "MH/s"

Result Line:

No Test Results

Result Key: #_RESULT_#

Template Line: [2017-12-10 18:07:01] Benchmark: #_RESULT_# kH/s

Result Parsing Search Key: "kH/s"

Result Line:

No Test Results

The test run did not produce a result.

Log File At: C:\Users\Bomarc\.phoronix-test-suite\installed-tests\pts\cpuminer-opt-1.3.0\cpuminer-opt-1.3.0-1601096912-1.log

========================================
Cpuminer-Opt (Run 1 of 1)
========================================

Test Run Command: cd C:\Users\Bomarc\.phoronix-test-suite\installed-tests\\pts/cpuminer-opt-1.3.0\ && ./cpuminer-opt -a sha256t 2>&1

         **********  cpuminer-opt 3.8.8.1  ***********
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

CPU:         Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz.
SW built on May 11 2018 with GCC 5.3.1.
CPU features: SSE2 AES SSE4.2 AVX.
SW features: SSE2 AES SSE4.2 AVX AVX2.
Algo features: SSE4.2 AVX2 SHA.
The SW build requires a CPU with AES and AVX2!

Result Key: #_RESULT_#

Template Line: [2017-12-10 18:07:01] Benchmark: #_RESULT_# MH/s

Result Parsing Search Key: "MH/s"

Result Line:

No Test Results

Result Key: #_RESULT_#

Template Line: [2017-12-10 18:07:01] Benchmark: #_RESULT_# kH/s

Result Parsing Search Key: "kH/s"

Result Line:

No Test Results

The test run did not produce a result.

Log File At: C:\Users\Bomarc\.phoronix-test-suite\installed-tests\pts\cpuminer-opt-1.3.0\cpuminer-opt-1.3.0-1601096923-1.log

The following tests failed to properly run:

    - pts/cpuminer-opt-1.3.0: Algorithm: m7m
    - pts/cpuminer-opt-1.3.0: Algorithm: deep
    - pts/cpuminer-opt-1.3.0: Algorithm: lbry
    - pts/cpuminer-opt-1.3.0: Algorithm: skein
    - pts/cpuminer-opt-1.3.0: Algorithm: myr-gr
    - pts/cpuminer-opt-1.3.0: Algorithm: sha256t

**Comment by michaellarabel** [comment]
At this point it's not surprise as cpuminer-opt is optimized for modern CPU architectures. It really isn't worthwhile pursuing a build for pre-AVX2 processors given AVX2 has been widely available for so long already and most PTS users on x86_64 are using AVX2 enabled CPUs.
