### ISSUE TITLE
Gcrypt installation error

### ISSUE THREAD

**Issue by multiflexi** [phoronix-test-suite/test-profiles#17]
[install.log](https://github.com/phoronix-test-suite/test-profiles/files/1974244/install.log)
On Ubuntu 18.04 - happens in .deb version and git branch 7.8
At the end there is double // in...gcrypt-1.0.4//gpgerror/... all I can say

**Comment by michaellarabel** [comment]
Installing libgpg-error via your Ubuntu package manage should correct this error though on my testing of Ubuntu 18.04 I haven't hit this issue.
