### ISSUE TITLE
Add WebP2 (libwebp2) benchmark profile

### ISSUE THREAD

**Issue by EwoutH** [phoronix-test-suite/test-profiles#185]
Google is working on a successor of the WebP format, WebP2. Would be cool to have an early benchmark profile, they say it's fully multi-threaded.

> **WebP 2**
> WebP 2 is the successor of the WebP image format, currently in development. It is not ready for general use, and the format is not finalized so changes to the library can break compatibility with images encoded with previous versions.
> USE AT YOU OWN RISK!
> 
> This package contains the library that can be used in other programs to encode or decode Webp 2 images, as well as command line tools.

- Git repo: https://chromium.googlesource.com/codecs/libwebp2/
- Windows (x64) builds: https://ci.appveyor.com/project/EwoutH/libwebp2/build/artifacts

**Comment by michaellarabel** [comment]
Yeah WebP2 is interesting and hadn't looked at it since the initial Git repo went public. Looks far enough along now that a webp2 test profile is available based on the existing webp test profile and same input.

https://openbenchmarking.org/test/pts/webp2-1.0.0
