### ISSUE TITLE
pts/aom-av1 doesnt reflect possible parallelism

### ISSUE THREAD

**Issue by kkartaltepe** [phoronix-test-suite/test-profiles#188]
Current test suites are all run without any tiling, this prevents parallelism with multiple threads entirely in RT mode.

Im not sure if adding tiling to all test cases is appropriate but at least showing a test case with tiling to show the potential impact of multiple threads seems appropriate.
```
--tile-columns=Y
--tile-rows=X
```
Are the associated flags, 2 or 4 tiles seem common (e.g. Y=1,X=0 and Y=1,X=1).

**Comment by michaellarabel** [comment]
The existing aom-av1 options were based on suggestions from a feature request originally from the user asking the libaom test be added. But, yes, sure thing it makes sense adding some run options with the tiling options and I must have overlooked those options previously. So, yes, I will explore some reasonable additional options for the next test profile update of it. Thanks.

**Comment by michaellarabel** [comment]
Increasing the time-column/tile-row settings with the test profile update to libaom-2.1-rc1. Thanks.
