### ISSUE TITLE
.mov is not supported by vpxenc

### ISSUE THREAD

**Issue by johannkoenig** [phoronix-test-suite/test-profiles#19]
https://github.com/phoronix-test-suite/test-profiles/blob/572a2b009e4df1ab05d299ce0c584b13819de478/pts/vpxenc-2.0.0/downloads.xml#L12

vpxenc requires yuv or y4m input. The mov file is being treated as yuv. Playing the video back will just show random snow.

**Comment by michaellarabel** [comment]
That issue was fixed in vpxenc-2.1 but this bug wasn't closed.

http://openbenchmarking.org/test/pts/vpxenc
