### ISSUE TITLE
add vkpeak

### ISSUE THREAD

**Issue by nihui** [phoronix-test-suite/test-profiles#192]
Hello !

I have created a tool which profiles Vulkan devices to find their peak capacities, called vkpeak

https://github.com/nihui/vkpeak

The idea of the vkpeak name comes from clpeak, which is for opencl devices.

The prebuild binaries for Linux Windows and MacOS are available at https://github.com/nihui/vkpeak/releases

Thanks !

The output info is formatted like

```
[nihui@nihui-pc build]$ ./vkpeak 0
device       = GeForce RTX 2070

fp32-scalar  = 8536.18 GFLOPS
fp32-vec4    = 8473.82 GFLOPS

fp16-scalar  = 8405.30 GFLOPS
fp16-vec4    = 16261.30 GFLOPS

fp64-scalar  = 262.86 GFLOPS
fp64-vec4    = 262.86 GFLOPS

int32-scalar = 8363.63 GIOPS
int32-vec4   = 8313.07 GIOPS

int16-scalar = 5518.05 GIOPS
int16-vec4   = 7138.91 GIOPS
```

**Comment by michaellarabel** [comment]
Interesting, thanks. Will check it out. Though at the moment the releases page appears empty?

**Comment by nihui** [comment]
> Interesting, thanks. Will check it out. Though at the moment the releases page appears empty?

I am trying to fix the release script at the moment. It should be ready sometime later.

**Comment by nihui** [comment]
> Interesting, thanks. Will check it out. Though at the moment the releases page appears empty?

Binary packages are available now  :)

**Comment by michaellarabel** [comment]
Thanks, seems to be working out fine now. 

https://openbenchmarking.org/test/pts/vkpeak
