### ISSUE TITLE
AOM AV1 v3.1.0

### ISSUE THREAD

**Issue by EwoutH** [phoronix-test-suite/test-profiles#196]
Earlier this week aom [v3.1.0 Celestia](https://aomedia.googlesource.com/aom/+/refs/tags/v3.1.0) was released. Could the [AOM AV1](https://openbenchmarking.org/test/pts/aom-av1) profile be updated?

**Comment by michaellarabel** [comment]
When looking at the change-log, the libaom 3.1 changes seemed to be primarily for AVIF so not sure there is much significant performance difference for updating the aom-av1 test profile from 3.0.

**Comment by EwoutH** [comment]
Thanks for the quick reply! Most improvements are for intra-encoding indeed, but there are also some nice improvements for the other 2-pass and realtime speed profiles. You can [compare the two tags](https://github.com/jbeich/aom/compare/v3.0.0...v3.1.0) here, a few examples:

- Re-enable tpl multithreading for speed 0, 1
- Increase recode tolerence for speed 2
- Extend speed feature txfm_rd_gate_level to speed 2
- AV1 RT: Fix speed 6 quality degradation on mid res
- Allow rectangular coding block to search txfm sizes in speed 6 
- Disable LAST2 and ALTREF2 reference frames in speed 6. 
- No second MV search for speed >= 3
- Speed up speed 3 by enabling some speed features
- Speed up speed 2 by enabling some conservative speed features

**Comment by michaellarabel** [comment]
Seeing some gains (3.0 vs. 3.1 - https://openbenchmarking.org/result/2105062-PTS-LIBAOM3139 ) so went ahead and pushed pts/aom-av1-2.4.0 against libaom 3.1. Thanks.

**Comment by EwoutH** [comment]
Awesome, thanks for verifying it!
