### ISSUE TITLE
libgav1 v0.16.3

### ISSUE THREAD

**Issue by EwoutH** [phoronix-test-suite/test-profiles#197]
Mid-april libgav1 [v0.16.3](https://chromium.googlesource.com/codecs/libgav1/+/refs/tags/v0.16.3) was released. Since the current [libgav1 profile](https://openbenchmarking.org/test/pts/libgav1) is from november 2019, this might be a nice time to update it.

**Comment by michaellarabel** [comment]
pts/libgav1-1.1.0 is now available that updates against the new release. Thanks.
