### ISSUE TITLE
pts/cuda-mini-nbody

### ISSUE THREAD

**Issue by swarth100** [phoronix-test-suite/test-profiles#21]
I would like to propose a change to the cuda mini-nbody as it is currently overall execution time (sys.time), rather than actually using the performance information provided by the benchmark itself.

PREMISE:
To get this information I suggest to allow the **seconds per iteration** metric to be exposed from within the individual cuda sources. In a simple hacky way, it could be done as follows:
```
#ifndef SHMOO
    printf("Iteration %d: %.3f seconds\n", iter, tElapsed);
#endif
```
to:
```
    printf("Iteration %d: %.3f seconds\n", iter, tElapsed);
```

Now lets look at what running the `shmoo-cuda-nbody-orig.sh` outputs with this change:
```
NVIDIA TITAN XP
nbody-orig
[...]
Iteration 1: 1.254 seconds
Iteration 2: 1.261 seconds
Iteration 3: 1.258 seconds
Iteration 4: 1.259 seconds
Iteration 5: 1.259 seconds
Iteration 6: 1.245 seconds
Iteration 7: 1.258 seconds
Iteration 8: 1.250 seconds
Iteration 9: 1.259 seconds
Iteration 10: 1.259 seconds
524288, 218.758
```
```
NVIDIA TESLA V100
nbody-orig
Iteration 1: 0.561 seconds
Iteration 2: 0.584 seconds
Iteration 3: 0.564 seconds
Iteration 4: 0.584 seconds
Iteration 5: 0.604 seconds
Iteration 6: 0.584 seconds
Iteration 7: 0.564 seconds
Iteration 8: 0.564 seconds
Iteration 9: 0.563 seconds
Iteration 10: 0.564 seconds
524288, 477.949
```

There are 2 metrics which are **more significant than overall execution time**:
1. The time it takes to perform an iteration with the larges nBody (524288) is significant.
1. The result on the final (nBodies * nBodies / avgTime) for the largest nBody (524288) is also a lot more significant than execution time.

Why am I stating this?
Well, when I simply run the test as it currently is:
```
TITAN XP
$ phoronix-test-suite run pts/cuda-mini-nbody

[...]
    Average: 17.89 Seconds
    Deviation: 0.49%
```
```
TESLA V100
$ phoronix-test-suite run pts/cuda-mini-nbody
[...]
    Average: 26.91 Seconds
    Deviation: 3.25%
```
We see that even though the V100 tecnically is 2 times faster at executing the test, it seems to be outperformed by the TitanXP

- - -
Hence the simple fix is to change the `results-definition.xml` for this test to:
```
<?xml version="1.0"?>
<!--Phoronix Test Suite v6.4.0-->
<PhoronixTestSuite>
  <ResultsParser>
    <OutputTemplate>524288, #_RESULT_# </OutputTemplate>
    <LineHint>524288,</LineHint>
    <ResultScale>(NBody^2)/s</ResultScale>
    <ResultProportion>LIB</ResultProportion>
  </ResultsParser>
</PhoronixTestSuite>
```

**Comment by michaellarabel** [comment]
I'm certainly not opposed to changing it to reporting seconds/iteration. I think when originally creating that basic test profile, I hadn't seen that ifdef. Would you be able to prepare a patch for it? (I don't have a CUDA setup handy at the moment, but if you can get a patch that could then be included in the test profile, I can more quickly get the test profile updated. The patch could just be tossed into the test profile's install.sh install script. Thanks.)

**Comment by michaellarabel** [comment]
Apologies for the delay in losing track of this thread until working on some CUDA tests this week... Anyhow, it's now been merged and available to PTS users. Thanks.
