### ISSUE TITLE
Add pyperformance (The Python Benchmark Suite) test profile

### ISSUE THREAD

**Issue by EwoutH** [phoronix-test-suite/test-profiles#225]
Add a test profile for The Python Benchmark Suite, also know as pyperformance, to the Phoronix Test Suite.

> ### The Python Performance Benchmark Suite
> The pyperformance project is intended to be an authoritative source of benchmarks for all Python implementations. The focus is on real-world benchmarks, rather than synthetic benchmarks, using whole applications when possible.
> 
> - [pyperformance documentation](http://pyperformance.readthedocs.io/)
> - [pyperformance GitHub project](https://github.com/python/pyperformance) (source code, issues)
> - [Download pyperformance on PyPI](https://pypi.python.org/pypi/pyperformance)
> 
> pyperformance is distributed under the MIT license.

**Comment by michaellarabel** [comment]
PyPerformance has already been available in PTS since 2020.

`phoronix-test-suite benchmark pyperformance`
