### ISSUE TITLE
system/blender(-1.0.2) cpu profiles still use gpu based files

### ISSUE THREAD

**Issue by grooverdan** [phoronix-test-suite/test-profiles#24]
When a system/blender test is run the process list shows that the gpu file is being run. The GPU file contains a tile size of 256x256 which for a single frame JPEG render limits the number of CPUs being used.

The cpu blend files in cycles_benchmark_20160228 contain a 32x32 tile size and is configured for CPU.

https://openbenchmarking.org/test/pts/blender version 1.4.1 contains a `BLEND_ARGS=${BLEND_ARGS/_gpu/_cpu}` fix in the generated `blender` when a CPU profile is selected.

**Comment by michaellarabel** [comment]
system/blender-1.1.0 is now available that uses the BLEND_ARGS handling similar to the pts/blender test - http://openbenchmarking.org/test/system/blender-1.1.0

Thanks for the report.
