### ISSUE TITLE
No "benchmark/benchmark.h" in pts/mutex-1.0.0

### ISSUE THREAD

**Issue by intelmy** [phoronix-test-suite/test-profiles#246]
Missing header file in this pts test package, results to it cannot be compiled successfully:

$ tar xvf BenchmarkMutex-1.tar.xz
BenchmarkMutex.cpp

where i can find this "benchmark/benchmark.h" as used by above cpp file

**Comment by michaellarabel** [comment]
https://github.com/google/benchmark needs to be installed on the system.
