### ISSUE TITLE
glmark2-1.0.2 can not be installed on Ubuntu 17.04

### ISSUE THREAD

**Issue by fatal-man** [phoronix-test-suite/test-profiles#3]
when installing glmark2-1.0.2 on Ubuntu 17.04 a number of errors occur.

These Issues I manually corrected in my local glmark2-rev276.tar.bz2 and then the installation was successful:
check C libraries using the C compiler in wscript
https://github.com/glmark2/glmark2/commit/88bbc8383fbf8c0ddf5cd133c086df5173975d82

Support libpng 1.6 in wscript (libpng12-0 v1.2.54-1ubuntu1 on my machine was not detected)
https://github.com/glmark2/glmark2/commit/499aa81a68fb4c8aac1c80f0d6a4cce05941c4cc

Replace the use of the deprecated auto_ptr with unique_ptr in src/image-reader.cpp, src/model.cpp, src/scene-jellyfish.cpp and src/libmatrix/shader-source.cc
https://github.com/glmark2/glmark2/commit/3137e5c184581c9a69c687ecf46ba08f02c4117b

Make sure to include cstring for 'memcpy' declaration in src/image-reader.cpp
https://github.com/glmark2/glmark2/commit/55848224375f4a980d5b83ef475e8cf1a6532d47

C++11 requires a space between literal and string macro
in src/native-state-x11.cpp
https://github.com/glmark2/glmark2/commit/1ac261a744841d90800fe02cf9a58ddc29b3137e
in src/native-state-mir.cpp
https://github.com/glmark2/glmark2/commit/a8d0f41f99c2d71740b68e00bacab11eefb0530c

**Comment by michaellarabel** [comment]
This issue is fixed with pts/glmark2-1.1 [ http://openbenchmarking.org/test/pts/glmark2-1.1.0 ] with now updating the glmark2 copy against the latest Git.

Thanks.
