### ISSUE TITLE
pts/parboil not running in systems where python3 is the default

### ISSUE THREAD

**Issue by aduenasd** [phoronix-test-suite/test-profiles#31]
pts/parboil scripts are python2 code and they assume python2 is your default. In systems with python3 as default pts/parboil will not at all.

**Comment by michaellarabel** [comment]
pts/parboil-1.1.3 fixes the python handling and checks first to ensure python2 is in the path otherwise will stick to using `python` if `python2` is not found.

**Comment by aduenasd** [comment]
Hi Michael, thanks for fixing this!
I tried the new parboil-1.1.3 but I'm still getting errors of python2 vs python3 syntax:
Test Run Command: cd /var/lib/phoronix-test-suite/installed-tests/pts/parboil-1.1.3/ && ./parboil cutcp omp_base large 2>&1                     
                                                                      
read 96603 atoms from file '/var/lib/phoronix-test-suite/installed-tests/pts/parboil-1.1.3/parboil-2.5-tree/datasets/cutcp/large/input/watbox.sl100.pqr'
extent of domain is:                                                                                                                                    
  minimum -49.998 -49.997 -49.996             
  maximum 50 49.99 49.971                                                                   
padding domain by 0.5 Angstroms      
domain lengths are 100.998 by 100.987 by 100.967      
                                                   
IO        : 0.121729                
Compute   : 24.261395                                              
Timer Wall Time: 24.383123                
Traceback (most recent call last):                      
  File "tools/compare-output", line 8, in <module>                              
    import filecompare as fc                                         
  File "/var/lib/phoronix-test-suite/installed-tests/pts/parboil-1.1.3/parboil-2.5-tree/common/python/filecompare.py", line 11
    raise TypeError, "Not a CompareMonad instance"
                   ^                                 
SyntaxError: invalid syntax     
Parboil parallel benchmark suite, version 0.2                                                                 
Output checking tool detected a mismatch                                                               
The test quit with a non-zero exit status.                                                                                                                                
E: SyntaxError: invalid syntax                                

My guess is that parboil-2.5-tree/benchmarks/cutcp/tools/compare-output is still pulling python2 via its shebang even when this file only contains function definitions and it's not executable per se
I've added more debug int cutcp/tools/compare-output:

Parboil parallel benchmark suite, version 0.2
read 96603 atoms from file '/var/lib/phoronix-test-suite/installed-tests/pts/parboil-1.1.3/parboil-2.5-tree/datasets/cutcp/large/input/watbox.sl100.pqr'
extent of domain is:
  minimum -49.998 -49.997 -49.996
  maximum 50 49.99 49.971
padding domain by 0.5 Angstroms
domain lengths are 100.998 by 100.987 by 100.967

IO        : 0.121003
Compute   : 24.270985
Timer Wall Time: 24.391989
split -S:  ‘python’
 into:    ‘python’
executing: python
   arg[0]= ‘python’
   arg[1]= ‘tools/compare-output’
   arg[2]= ‘/var/lib/phoronix-test-suite/installed-tests/pts/parboil-1.1.3/parboil-2.5-tree/datasets/cutcp/large/output/lattice.dat’
   arg[3]= ‘/var/lib/phoronix-test-suite/installed-tests/pts/parboil-1.1.3/parboil-2.5-tree/benchmarks/cutcp/run/large/lattice.dat’
Traceback (most recent call last):
  File "tools/compare-output", line 8, in <module>
    import filecompare as fc
  File "/var/lib/phoronix-test-suite/installed-tests/pts/parboil-1.1.3/parboil-2.5-tree/common/python/filecompare.py", line 11
    raise TypeError, "Not a CompareMonad instance"
                   ^
SyntaxError: invalid syntax
Output checking tool detected a mismatch

Actually if I remove the shebang from parboil-2.5-tree/benchmarks/cutcp/tools/compare-output the test runs ok....
I'll try to debug more and rule out my system/os/env ...
