### ISSUE TITLE
[pts/m-queens] update request

### ISSUE THREAD

**Issue by sudden6** [phoronix-test-suite/test-profiles#39]
Based on your newest 128 Thread EPYC tests I noticed a bottleneck in m-queens for high thread counts. 

Please update the profile to use https://github.com/sudden6/m-queens/releases/tag/v1.2 

Note: This release also contains some other optimizations so that the performance is not really comparable.

Additionally, would you mind running a comparison for this program between some ARM or PowerPC system and x86_64?

**Comment by michaellarabel** [comment]
pts/m-queens-1.1.0 is now available  via OpenBenchmarking.org that re-bases against the M-Queens 1.2 release. That version bump (as opposed to moving to 1.0.2) also ensures PTS doesn't compare any old/new results that they are rendered separately.

Unfortunately I have no direct POWER access yet. I will be using this new m-queens test profile in an upcoming Xeon/EPYC comparison and will eventually get into next ARM benchmarking roundabout when that happens. Thanks.
