### ISSUE TITLE
glibc benchmarks are unreliable and produce incorrect results

### ISSUE THREAD

**Issue by atomsymbol** [phoronix-test-suite/test-profiles#44]
The glibc benchmarks (glibc-benchmarks-1.tar.gz) are unreliable and are generating incorrect results because their aren't compiled with USE_CLOCK_GETTIME=1.

**Incorrect** result for `bench-ffs` (glibc-benchmarks-1.tar.gz, Ryzen 5 1600):

    "ffs": {
     "": {
      "duration": 3.18057e+09,
      "iterations": 4.975e+08,
      "max": 26.368,
      "min": 6.048,
      "mean": 6.3931
     }
    }

**Correct** result for `bench-ffs` (USE_CLOCK_GETTIME=1, glibc 2.27, Ryzen 5 1600):

    "ffs": {
     "": {
      "duration": 9.3078e+09,
      "iterations": 4.3072e+09,
      "max": 8.67,
      "min": 2.04,
      "mean": 2.16099
     }
    }

**Suggested resolution**: Compile glibc benchmarks via `make USE_CLOCK_GETTIME=1 bench-build`, package it as glibc-benchmarks-2.tar.gz and create new version glibc-bench-1.6 (version numbers may vary).

**Comment by michaellarabel** [comment]
Hi @VictorRodriguez as you made the glibc-bench test originally, is there any reason you opted for not using USE_CLOCK_GETTIME or any objection to this change?

**Comment by atomsymbol** [comment]
The default when building glibc benchmarks is to avoid USE_CLOCK_GETTIME if possible. In this case the benchmarks use RDTSC to do the time measurements. However, the way in which the benchmarks are using RDTSC is unreliable (I did not investigate why), and widely changes the measured result when you overclock the (Ryzen) CPU.

**Comment by VictorRodriguez** [comment]
The background of this tests is to have a binary that measures the speed of many glibc functions, the src of the binaries  are taken from make bench from glibc master branch, The binaries are taken from Fedora release. As you can see : https://openbenchmarking.org/innhold/5da9edb6f23783051658fc07d40105b95eb77ea9
the test is not compiled just under and execute the binaries . 

In order to make the test be compiled every time it is executed is necessary to isolate the tests from glibc master and compile them. I could work on that , but sure not on the short term 

All patches are more than welcome

**Comment by atomsymbol** [comment]
I have built the benchmarks (glibc-2.28) and generated glibc-benchmarks-2.tar.gz file:

[glibc-benchmarks-2.tar.gz](https://github.com/phoronix-test-suite/test-profiles/files/2594985/glibc-benchmarks-2.tar.gz)

glibc-benchmarks/README contains build instructions.

You can upload the file to openbenchmarking.org.

**Comment by michaellarabel** [comment]
@VictorRodriguez apologies for the delay, the file should be uploaded @ https://www.phoronix-test-suite.com/benchmark-files/glibc-benchmarks-2.tar.gz

**Comment by atomsymbol** [comment]
@VictorRodriguez I filed a glibc bug report (https://sourceware.org/bugzilla/show_bug.cgi?id=23922) and their conclusion is that the RDTSC-based measurements are **unitless** which means they are non-comparable across different CPUs.

**Comment by VictorRodriguez** [comment]
@atomsymbol sorry fro delay , ls the new version of the test compiled with USE_CLOCK_GETTIME=1 ok ? or the glibc test is not good for across different CPUs. as it is ?

**Comment by atomsymbol** [comment]
@VictorRodriguez Yes, the new version compiled with USE_CLOCK_GETTIME=1 is OK as it generates results in nanoseconds.

Without USE_CLOCK_GETTIME=1 the result depends on TSC (Time Stamp Counter) frequency which varies between CPUs. To get nanoseconds the result would have to be divided by the TSC frequency.

It is expected that the RDTSC result and CLOCK_GETTIME result differ from each other for the same benchmark. For example, if the TSC frequency is 3.5GHz then the two results should differ by a factor of approximately 3.5.

**Comment by atomsymbol** [comment]
> @atomsymbol can you please test PR : [VictorRodriguez@ff7ba3b](https://github.com/VictorRodriguez/test-profiles/commit/ff7ba3b7e9b6c582f7578c27d349a60fd436b7bc) and let me know if is ok ?

Installs and runs OK on my machine.

**Comment by VictorRodriguez** [comment]
@michaellarabel we can merge the PR if you want

**Comment by michaellarabel** [comment]
Thanks @VictorRodriguez and @atomsymbol this has been merged as pts/glibc-bench-1.6.0 (the larger version bump so users cannot compare new results to old data with the timing being different.)
