### ISSUE TITLE
clpeak: multiple platforms

### ISSUE THREAD

**Issue by atomsymbol** [phoronix-test-suite/test-profiles#56]
Hello.

The `clpeak` benchmark does not generate correct results on my machine. I have 3 OpenCL platforms, each platform has a single device. Running `clpeak` in PTS unexpectedly records the performance of the last platform, not the first platform.

In order to product correct results, PTS needs to additionally pass `-p 0` to `clpeak` to select the first platform:

    clpeak -p 0 -d 0 --compute-sp

Currently, only `-d 0` is passed to clpeak, generating the following (incorrect) results:

    $ ./clpeak -d 0 --compute-sp
    Platform: AMD Accelerated Parallel Processing
      Device: Hawaii
        Single-precision compute (GFLOPS)
          float   : 5057.77
          float2  : 5051.59
          float4  : 5034.63
          float8  : 5012.79
          float16 : 4959.53
    
    Platform: NVIDIA CUDA
      Device: GeForce GTX 750
        Single-precision compute (GFLOPS)
          float   : 714.02
          float2  : 1104.40
          float4  : 1171.74
          float8  : 1104.74
          float16 : 1161.95
    
    Platform: Intel(R) OpenCL
      Device: AMD Ryzen 5 1600 Six-Core Processor            
        Single-precision compute (GFLOPS)
          float   : 133.67
          float2  : 265.19
          float4  : 328.40
          float8  : 133.27
          float16 : 239.27

**Comment by michaellarabel** [comment]
With pts/clpeak-1.0.1 test profile now available and newer, the first platform is now set. Thanks.

https://openbenchmarking.org/test/pts/clpeak-1.0.1

**Comment by atomsymbol** [comment]
Works as expected. Thanks.
