### ISSUE TITLE
Civilization VI broken

### ISSUE THREAD

**Issue by random2324** [phoronix-test-suite/test-profiles#59]
Used to work before just shows the initial aspyr launcher.

**Comment by michaellarabel** [comment]
Yes, a Civilization VI update on Steam unfortunately dropped the benchmark functionality, unfortunately... I have yet to hear whether they plan to restore said functionality or not. Otherwise, unfortunately, there is no workaround.

**Comment by random2324** [comment]
Okay thx -the test should be marked as non-working then.

**Comment by michaellarabel** [comment]
Yep I intend to mark it as deprecated unless I see it fixed in the next few weeks. Just been waiting to see if any updates will correct it soon and since the test profile still works fine for anyone who keeps their Steam library in offline mode on an older version for the time being.

**Comment by michaellarabel** [comment]
The test profile was recently updated as the latest Steam builds of Civilization VI should work out fine (finally) for benchmarking once again. Thanks.

https://openbenchmarking.org/test/pts/civilization-vi
