### ISSUE TITLE
Add SVT-VP9 test profile

### ISSUE THREAD

**Issue by EwoutH** [phoronix-test-suite/test-profiles#62]
SVT-VP9 is released on GitHub: https://github.com/OpenVisualCloud/SVT-VP9

Probably a modified version of SVT-AV1 can be used.

**Comment by michaellarabel** [comment]
Thanks for pointing out their new VP9 encoder! Test profile added @ https://openbenchmarking.org/test/pts/svt-vp9-1.0.0 pts/svt-vp9 using the same input file as the other SVT test profiles.
