### ISSUE TITLE
Update SVT-AV1 with live preset

### ISSUE THREAD

**Issue by EwoutH** [phoronix-test-suite/test-profiles#72]
With the latest commit [SVT-AV1](https://github.com/OpenVisualCloud/SVT-AV1) got higher presets for faster encodes. Aside from the currently used `-enc-mode 3`, a test run with `-enc-mode 7` would be great to test live encoding. Soon 1080p 30fps will be possible on high-end consumer hardware.

**Comment by michaellarabel** [comment]
The default according to the documentation and from testing (and thus what's been the default for PTS thus far with not specifying -enc-mode) is already 7. But looking at adding 0 / 3 / 7 options to the test profile now.

**Comment by EwoutH** [comment]
@michaellarabel Ah in that case they changed it from 3 to 7. 

0 / 3 / 7 would be great!
