### ISSUE TITLE
Measure CPU usage in video encoding tests, maybe others

### ISSUE THREAD

**Issue by veikk0** [phoronix-test-suite/test-profiles#74]
Being able to see the average CPU usage of video encoder tests could be very useful for judging how well an encoder scales across multiple cores. This would be especially useful for libvpx and libaom that currently don't scale as well as, say, x264 and x265.

I'm not sure how to best measure the average CPU usage of a process on all the platforms supported by PTS, but on Linux you can prepend a command with `/usr/bin/time -f "%P"` and the average CPU usage of the appended command will be printed after it has run. Note, `/usr/bin/time` is required because `time` invokes a different, built-in time command of most shells.

This could also be useful in other benchmarks, although average CPU usage across all cores/threads is quite a simplistic metric.

**Comment by michaellarabel** [comment]
It's already possible for any test profile. Simply set the MONITOR environment variable to the sensors you want to measure, e.g.

MONITOR=cpu.usage,cpu.temp,mem.usage phoronix-test-suite benchmark x264 x265

And it will generate CPU usage graphs in real-time for each graph.
