### ISSUE TITLE
Update SVT-AV1

### ISSUE THREAD

**Issue by EwoutH** [phoronix-test-suite/test-profiles#75]
SVT-AV1 just got a huge update (https://github.com/OpenVisualCloud/SVT-AV1/commit/47af208baf2c4bde185f437b9269f09e8fe3fbfb) which improves both coding efficiency and performance.

3 different runs with `-enc-mode 8`, `-enc-mode 4` and `-enc-mode 0` would still be really nice (#72).

**Comment by michaellarabel** [comment]
pts/svt-av1-1.3.0 is now available that pulls in the recent v0.5 upstream release. Thanks.

**Comment by EwoutH** [comment]
@michaellarabel Could you add a CPU with AVX512 to run the video benchmarks on [linuxbenchmarking.com](http://linuxbenchmarking.com/?video-benchmarks)? A lot of AVX512 SIMD code will be merged soon, so that would help to track performance.

A SVT-AV1 Git profile with a slower preset (such as `-enc-mode 3` would also be extremely helpful!

**Comment by michaellarabel** [comment]
@EwoutH I will need to check and see if I have any X-Series CPUs spare I could dedicate to this task. I have no extra Xeon Scalable (in fact, very few in general). I might have like a ~7900X system that I might be able to task, will check to see.

**Comment by EwoutH** [comment]
@hassount Might you be able to help out here?
