### ISSUE TITLE
pts/compress-xz

### ISSUE THREAD

**Issue by jnettlet** [phoronix-test-suite/test-profiles#76]
was doing system profiling while running the benchmark suite and noticed that the pts/compress-xz test was not using all the cores on my system.  After testing options by hand it appears that level 9 only uses 5 cores maximum, and level 8 only 9.  It isn't until I drop down to level 7 that all cores on the system were utilized.

Is this the expected results of the test?   It seems like using the default compression level would be the most real world benchmark since that is what most users would invoke.

**Comment by michaellarabel** [comment]
Thanks for doing the profiling and bringing this to my attention , pts/compress-xz-1.1.0 is now available that uses a compression level of 7.
