### ISSUE TITLE
pts/apache-siege requires /usr/local/var

### ISSUE THREAD

**Issue by Sayrus** [phoronix-test-suite/test-profiles#77]
`pts/apache-siege` requires `/usr/local/var` to create the siege.log file.
If it does not exists, the test crash. Maybe it should be created on install?

This directory does not exists at least on Arch Linux.

```
LOG FILE: /usr/local/var/siege.log
You can disable this log file notification by editing
/var/lib/phoronix-test-suite/installed-tests/pts/apache-siege-1.0.2//.siege/siege.conf and changing 'show-logfile' to false.
[error] unable to create log file: /usr/local/var/siege.log: No such file or directory
```

Creating the missing var directory solves the problem.

**Comment by michaellarabel** [comment]
The updated test profile now passes --log= argument so it should be logging in the current directory rather than attempt in /usr/... Thanks for reporting this.
