### ISSUE TITLE
mkl-dnn: wrong parameters

### ISSUE THREAD

**Issue by rsdubtso** [phoronix-test-suite/test-profiles#78]
Hi! First of all, thanks for packaging this. I noticed a few issues:

1. There is a bug in `tests-definitions.xml` for the mkl-dnn profile: the resulting benchdnn command line is incorrect.

Currently produced command line:
```sh
benchdnn --conv --batch=inputs/conv_alexnet --cfg=u8s8s32
```
this will actually run `f32` configuration because parameters are positional.

Correct command line is
```sh
benchdnn --conv --cfg=u8s8s32 --batch=inputs/conv_alexnet 
```

This is one of the reasons why in your Skylake vs Cascadelake testing you see no difference between the configurations.

2. Affinity is not set up in `install.sh`. The most portable setting for Linux compilers is probably via 
```sh
export OMP_PLACES=cores
export OMP_PROC_BIND=close
```
Additionally, it would probably best to test just a single socket, but this is up to you guys to decide.

**Comment by michaellarabel** [comment]
Hi Roma, thanks for the feedback. I was thinking some of the results were a bit unusual. For helping others in the future perhaps might it be useful to error out the program when the parameters positioning is invalid?

Will get the test profile updated shortly.

**Comment by rsdubtso** [comment]
The problem is that the parameters are technically valid -- benchdnn just expects another set of problem sizes after `--cfg=foo`. One could do `benchdnn --conv --cfg=f32 <problems> --cfg=u8s8s32 <other problems> ...`. We could probably print a warning, though (like `unused argument` or something).

**Comment by michaellarabel** [comment]
pts/mkl-dnn-1.0.2 is now available that should correct these issues (currently being tested).

https://openbenchmarking.org/innhold/61fa4385bc46f755cbf36ff75615414b020e6bab

Thanks again for reporting, will have some new tests soon.

**Comment by rsdubtso** [comment]
Just curious: are you going to publish new benchmarks any time soon?

**Comment by michaellarabel** [comment]
@rsdubtso Some newer data of the updated test profile can be found @ https://openbenchmarking.org/test/pts/mkl-dnn including for Cascadelake hardware. As for when will be in the next Phoronix article, not sure off top of my head for when I'll have time to finish up a new proper comparison. 

Do e.g. https://openbenchmarking.org/result/1905231-HV-MKLDNNCAS40 these cascadelake numbers look in line with expectations? Thanks.
