### ISSUE TITLE
pts/crafty | Obsolete crafty-23.4.zip URL

### ISSUE THREAD

**Issue by airvzxf** [phoronix-test-suite/test-profiles#8]
In Linux is replace the URL:
http://www.craftychess.com/crafty-23.4.zip
to
http://www.craftychess.com/downloads/source/crafty-23.4.zip

Also the file size, MD5 and SHA256 sums.

**Comment by airvzxf** [comment]
Of course I don't have permissions to push my local changes.

> remote: Permission to phoronix-test-suite/test-profiles.git denied to airvzxf.
> fatal: unable to access 'https://github.com/phoronix-test-suite/test-profiles.git/': The requested URL returned error: 403

**Comment by michaellarabel** [comment]
pts/crafty-1.4.0 is now available with the latest Crafty release and updated download mirrors.
