### ISSUE TITLE
Fix AOM AV1 benchmark on Linuxbenchmarking.com

### ISSUE THREAD

**Issue by EwoutH** [phoronix-test-suite/test-profiles#80]
The AOM AV1 probile on http://linuxbenchmarking.com/?video-benchmarks appears to be broken.

![Screenshot_443](https://user-images.githubusercontent.com/15776622/57912274-31edd180-788a-11e9-9655-722261aef357.png)

**Comment by michaellarabel** [comment]
Yeah it seems to have a build problem but didn't have a chance to look into it yet. Here is the Git version of that test profile if you happen to know offhand if there was any silly mistake in building aom-av1 from Git: https://openbenchmarking.org/innhold/6f1dc18c74138d78f81482b7e8908959641fe156

**Comment by michaellarabel** [comment]
The AOM-AV1 results should now be showing up, including all past results. The benchmarks were working correctly but it turns out there was a line graph bug when having mostly sub-1.0 data points that caused an issue in the graph generation that is now resolved.
