### ISSUE TITLE
pts/mysqlslap-1.0.6: missing dependency for zlib

### ISSUE THREAD

**Issue by squash** [phoronix-test-suite/test-profiles#81]
Ubuntu 18.04, zlib package is required to compile this test but is not specified as a dependency. Please add zlib1g-dev as an external dependency.

**Comment by michaellarabel** [comment]
pts/mysql-1.0.8 has been uploaded that adds zlib-development external dependency, which will install zlib1g-dev on Ubuntu systems. Thanks for reporting!
