### ISSUE TITLE
pts/vpxenc-2.3.0 Increase performance on multi-threaded machines

### ISSUE THREAD

**Issue by jnettlet** [phoronix-test-suite/test-profiles#83]
vpxenc is being called with threads and tile-columns, but this limits the maximum threading to only the columns of each frame which for 1080p is 4 threads.  Since version 1.7 there is another option --row-mt=1  which should be enabled that allows for additional parallel processing.  This option is also safe for systems that have less cores than tile-columns just won't provide as much of a significance in performance boost.  This allows all 16 cores to be utilized in this test.

**Comment by michaellarabel** [comment]
The pts/vpxenc-2.4.0 test profile is now out there that adds the "--row-mt=1" option.

Users can access this update via:

phoronix-test-suite openbenchmarking-refresh (to get updated meta-data if you've run the PTS in the past ~24 hours where it's using an outdated cache for the time being)

phoronix-test-suite benchmark vpxenc

Thanks for reporting this new option.
