### ISSUE TITLE
iperf produce incorrect result

### ISSUE THREAD

**Issue by jiebinn** [phoronix-test-suite/test-profiles#85]
location: ~/.phoronix-test-suite/test-profiles/pts/iperf-1.0.2/results-definition.xml

iperf can not produce a correct result for these following options.

    <Description>Duration: 10 Seconds - Test: TCP - Parallel: 10</Description>

    <Description>Duration: 10 Seconds - Test: UDP - Parallel: 5</Description>

    <Description>Duration: 10 Seconds - Test: UDP - Parallel: 10</Description>

    <Description>Duration: 10 Seconds - Test: UDP - Parallel: 20</Description>

    <Description>Duration: 10 Seconds - Test: UDP - 100Mbit Objective - Parallel: 5</Description>

    <Description>Duration: 10 Seconds - Test: UDP - 100Mbit Objective - Parallel: 10</Description>

The only way to get  the correnct result of 6 indicators is to delete the first two options in ~/.phoronix-test-suite/test-profiles/pts/iperf-1.0.2/results-definition.xml

**Comment by michaellarabel** [comment]
Apologies for the delay, a new iperf test profile was pushed out that fixes this issue.
