### ISSUE TITLE
iperf version 3.1.3 can't figure out the maximum UDP throughput when Linux kernel adopts fair-queue Qdisc policy

### ISSUE THREAD

**Issue by dapeng-mi** [phoronix-test-suite/test-profiles#86]
Currently phoronix adopts the iperf 3.1.3 version to run the iperf test. While there is an issue in iperf 3.1.3 version.  Iperf 3.1.3 would apply the application-level (user space) and fair-queuing-based (kernel space) pacing rate simultaneously base on the configured pumping rate (argument -b) for UDP stream. 

Iperf 3.1.3 would call the syscall "setsockopt(s, SOL_SOCKET, SO_MAX_PACING_RATE, &rate, sizeof(rate))"  to set the pacing rate into kernel fair-queue scheduler. fair-queue scheduler would calculate the maximum transmitting packets limit per second base on this pacing rate.  While the calculated packets limit is a little bit smaller than the idle value because the division is used and the decimal fraction is lost in the calculation.

A example running 100M pumping rate UDP stream test on 1000M Ethernet interface. The test distro is Clear Linux and the default qdisc policy is fair-queue (fq).

$ sysctl net.core.default_qdisc
net.core.default_qdisc = fq

iperf 3.1.3 test results:

dmi@dmi-i9-test~/.phoronix-test-suite/installed-tests/pts/iperf-1.0.3/iperf-install/bin $  ./iperf3 -c 10.239.159.127 -p 8000 -t 10 -u -b 100M -P 1 -f m -i 0 -l 8192
Connecting to host 10.239.159.127, port 8000
[  4] local 10.239.159.149 port 37766 connected to 10.239.159.127 port 8000
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-10.00  sec   115 MBytes  96.6 Mbits/sec  14736
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-10.00  sec   115 MBytes  96.6 Mbits/sec  0.102 ms  0/14726 (0%)
[  4] Sent 14726 datagrams

iperf Done.

we can see the UDP throughput is 96.6Mbps which is a little bit lower than the pumping rate 100Mbps.

Iperf version 3.1.5 has fixed the issue and won't set the fair-queuing-based (kernel space) pacing rate any more base on the configured pumping rate.

iperf 3.1.5 test result on same test case:

dmi@dmi-i9-test~/Downloads/iperf-3.1.5/install/bin $  ./iperf3 -c 10.239.159.127 -p 8000 -t 10 -u -b 100M -P 1 -f m -i 0 -l 8192
Warning:  UDP block size 8192 exceeds TCP MSS 1448, may result in fragmentation / drops
Connecting to host 10.239.159.127, port 8000
[  4] local 10.239.159.149 port 49987 connected to 10.239.159.127 port 8000
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-10.00  sec   118 MBytes  99.1 Mbits/sec  15123
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-10.00  sec   118 MBytes  99.1 Mbits/sec  0.103 ms  0/15123 (0%)
[  4] Sent 15123 datagrams

iperf Done.

we can see iperf 3.1.5 can figure out the more accurate ethernet bandwidth.  Iperf 3.1.3 is a quite old release version (almost 3 years ago), the latest iperf release version is 3.6. Is there any plan to upgrade iperf to 3.1.5 or later version? Thanks.

**Comment by michaellarabel** [comment]
pts/iperf-1.1.0 is now available that makes use of iperf 3.7 and other improvements. Sorry for losing track / looking over this ticket.
