### ISSUE TITLE
[FR]Specify workdir for iozone or just run it in current dir

### ISSUE THREAD

**Issue by yurikoles** [phoronix-test-suite/test-profiles#87]
I wanted to benchmark my data disk, but it seems like iozone always run on /home partition.

**Comment by michaellarabel** [comment]
Iozone is a rather poor test these days and the test profile for PTS of it has been deprecated. I would recommend using the `fio` test profile or other alternatives instead for better testing and there it should prompt you about alternative partitions to test.

**Comment by yurikoles** [comment]
Thanks, @michaellarabel!
