### ISSUE TITLE
[RFE] Upgrade tjbench to use libjpeg-turbo 2.0.2

### ISSUE THREAD

**Issue by flx42** [phoronix-test-suite/test-profiles#88]
I think `tjbench-1.0.2` is a useful benchmark for single-thread performance, but it currently uses libjpeg-turbo 1.5.3, I recommend upgrading to the latest version of libjpeg-turbo to benefit from the new algorithms implemented in AVX2, to at least get this one change:
https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/1.5.90

> Added AVX2 SIMD implementations of the colorspace conversion, chroma downsampling and upsampling, integer quantization and sample conversion, and slow integer DCT/IDCT algorithms. When using the slow integer DCT/IDCT algorithms on AVX2-equipped CPUs, the compression of RGB images is approximately 13-36% (avg. 22%) faster (relative to libjpeg-turbo 1.5.x) with 64-bit code and 11-21% (avg. 17%) faster with 32-bit code, and the decompression of RGB images is approximately 9-35% (avg. 17%) faster with 64-bit code and 7-17% (avg. 12%) faster with 32-bit code. (As tested on a 3 GHz Intel Core i7. Actual mileage may vary.)

From a quick testing I've done, the performance is indeed improved on newer Intel CPUs.

Thanks for the great work @michaellarabel!

**Comment by michaellarabel** [comment]
Thanks @flx42 wasn't aware of a new release. Will work on getting it updated in the days ahead.

**Comment by michaellarabel** [comment]
pts/tjbench-1.1.0 is now available via OpenBenchmarking.org that updates against upstream v2.0.2. Thanks!
