### ISSUE TITLE
pts/crafty-1.4.4 compilation fails on ARM

### ISSUE THREAD

**Issue by markku63** [phoronix-test-suite/test-profiles#89]
Crafty uses a x86-specific compiler flag (-mpopcount) and inline assembly code, so it should have `<SupportedArchitectures>x86, x86_64</SupportedArchitectures>` in its profile. See also: [https://github.com/phoronix-test-suite/phoronix-test-suite/issues/320](url)

**Comment by michaellarabel** [comment]
I've been waiting to see if Crafty upstream would add support for ARM or other architectures, but considering now, pts/crafty-1.4.5 is now set that limits the test for showing up on x86/x86_64. Thanks and sorry for the delay.
