### ISSUE TITLE
pts/tensorflow: missing dependency

### ISSUE THREAD

**Issue by greenduck** [phoronix-test-suite/test-profiles#9]
https://github.com/phoronix-test-suite/test-profiles/blob/0cb966241d99bf2040ec166b9190152be17280d2/pts/tensorflow-1.0.0/install.sh#L11

_python3-pip_ is not a required dependency, so it is not installed (Ubuntu 16.04). In addition, the output of _pip3 install tensorflow_ is not checked, so it silently fails, **but** the test **is** considered installed, so one must (1) install python3-pip, (2) remove-installed-test tensorflow, (3) install tensorflow again, which is a hassle.

**Comment by michaellarabel** [comment]
python3-pip has been added to the Ubuntu external dependency list for 'python', which this test profile depends upon: https://github.com/phoronix-test-suite/phoronix-test-suite/commit/e6c2387eac5dc6185bc6c0ed83a4b38e38358bd9

So if using latest PTS Git now, it should work on future installs of this test.
