### ISSUE TITLE
unexpected result in vpxenc test

### ISSUE THREAD

**Issue by tawm** [phoronix-test-suite/test-profiles#90]
When running the vpxenc test, only performance data from the first pass is used. The performance figures obtained like this do not reflect real world performance well, as the first pass is an order of magnitude faster than the second pass.

**Comment by veikk0** [comment]
To fix this, the `--passes=1` parameter should be used to produce a single-pass encode.

By default, vpxenc also uses a either vbr or cbr (cant remember which) at a very low bitrate. To activate the CRF equivalent intead, the parameters `--end-usage=cq` and `--cq-level=30` should be used.

aomenc is based on vpxenc and thus behaves the same way, so these options should probably be applied to that test profile as well.

**Comment by michaellarabel** [comment]
This should be fixed by pts/vpxenc-3.0.0. Thanks!
