### ISSUE TITLE
pts/encode-mp3 not enabling optimizations

### ISSUE THREAD

**Issue by jnettlet** [phoronix-test-suite/test-profiles#91]
This is a follow up to #36 the full optimizations are still not properly being applied.  We patch the configure.in script but then don't regenerate the configure script, which still leaves optimizations disabled.

After running
patch -p0 < power9-fix.patch

The install script then needs to run
autoconf

**Comment by michaellarabel** [comment]
Whoops, thanks for pointing that out. This has been fixed with pts/encode-mp3-1.7.4.
