### ISSUE TITLE
glibc-bench: enable more indicators 

### ISSUE THREAD

**Issue by wenhuanh** [phoronix-test-suite/test-profiles#92]
glibc-bench-1.6.0  has only 7 enabled indicators, some commonly used mathematical  functions are not enabled. More indicators may help better reflect the performance of glibc functions.
The new indicator patch is as attached, thanks.

[0001-Contribute-7-new-indicators-in-glibc-bench-1.6.0.zip](https://github.com/phoronix-test-suite/test-profiles/files/3519666/0001-Contribute-7-new-indicators-in-glibc-bench-1.6.0.zip)

new indicators:
Glibc-bench / asinh
Glibc-bench / atanh
Glibc-bench / sincos
Glibc-bench / sinh
Glibc-bench / modf
Glibc-bench / exp
Glibc-bench / log2

**Comment by michaellarabel** [comment]
Thanks, this patch is now applied with the pts/glibc-bench-1.6.1 update.
