### ISSUE TITLE
pts/sqlite

### ISSUE THREAD

**Issue by jnettlet** [phoronix-test-suite/test-profiles#96]
After reviewing some benchmark results I noticed that my sqlite benchmarks on an nvme drive were slower than a similar machine using slower storage medium.  In both cases there was very little cpu utilization and no iowait on the systems.  The sqlite default synchronous and journal modes were blocking waiting for the SSD to commit everything to disk, which is longer on the SSD files systems in order to consolidate writes and reduce disk wear.

This test as it is now seems to be more of a OS, file-system and storage medium test rather than a representative benchmark for sqlite performance.  I think using the sqlite speedtest1 utility is probably a better option.

If you download https://www.sqlite.org/src/tarball/sqlite.tar.gz?r=release it can easily be setup by just ./configure && make speedtest1  By default it does all the work in /var/tmp but a simple patch can change that location.

This is a single threaded test so it is limited by the performance of the single fastest core, but it does do some I/O and is a bit more representative of workload than just a series of inserts.  I would be happy to submit a pull request if the community would be interested in using this metric for evaluating sqlite performance.

**Comment by michaellarabel** [comment]
Sure I would be happy to either review such a new test profile or work on it myself. It may make sense to make it a new test profile like sqlite-speedtest as opposed to a new version over the existing sqlite test profile for those wishing to continue stressing the OS/file-system performance.

**Comment by michaellarabel** [comment]
There is now a pts/sqlite-speedtest test profile available. Though it's marked as a system test rather than disk I/O. When going through the code around the /var/tmp comment, SQLite should be honoring the SQLITE_TMPDIR / TMPDIR environment variables but in my testing of that it didn't appear to be the case. Anyhow, any patches/improvements beyond the initial sqlite-speedtest test profile are welcome.
